### PR TITLE
[RFR] Added a Node.js API

### PR DESCRIPTION
**Pull request by KittyGiraudel**
Would you mind reviewing this @schmkr? :)

### CODE REVIEW

**Comment by schmkr** [comment]
Very nice change! I'll see if I have some time to checkout and run the code + tests, but from the looking at the diffs, all seems good.

**Comment by KittyGiraudel** [comment]
I thought it would be a good idea to have a Node.js API as well as the CLI one. It makes it a bit more flexible and prevent having to use `child_process` just to run it from Node.

**Comment by schmkr** [comment]
Just ran the node api in our project and it seems to work perfect!

**Comment by KittyGiraudel** [comment]
Awesome, I’ll merge it right away. :)

**Pull request merged**
